# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt5.QtWidgets import (QApplication, QComboBox, QGraphicsView, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1303, 757)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(40, 90, 1261, 621))
        self.tabWidget.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setIconSize(QSize(100, 100))
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_bg = QWidget()
        self.tab_bg.setObjectName(u"tab_bg")
        self.pbBG = QPushButton(self.tab_bg)
        self.pbBG.setObjectName(u"pbBG")
        self.pbBG.setGeometry(QRect(580, 10, 93, 28))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.pbBG.setFont(font1)
        self.pilihMD = QComboBox(self.tab_bg)
        self.pilihMD.setObjectName(u"pilihMD")
        self.pilihMD.setGeometry(QRect(80, 10, 361, 22))
        self.pilihMJ = QComboBox(self.tab_bg)
        self.pilihMJ.setObjectName(u"pilihMJ")
        self.pilihMJ.setGeometry(QRect(880, 10, 361, 22))
        self.mdBG = QGraphicsView(self.tab_bg)
        self.mdBG.setObjectName(u"mdBG")
        self.mdBG.setGeometry(QRect(10, 50, 611, 241))
        self.mjBG = QGraphicsView(self.tab_bg)
        self.mjBG.setObjectName(u"mjBG")
        self.mjBG.setGeometry(QRect(630, 50, 611, 241))
        self.fftBG = QGraphicsView(self.tab_bg)
        self.fftBG.setObjectName(u"fftBG")
        self.fftBG.setGeometry(QRect(10, 300, 1231, 281))
        self.labelMD = QLabel(self.tab_bg)
        self.labelMD.setObjectName(u"labelMD")
        self.labelMD.setGeometry(QRect(10, 10, 61, 21))
        self.labelMD.setFont(font1)
        self.labelMD.setAlignment(Qt.AlignCenter)
        self.labelMJ = QLabel(self.tab_bg)
        self.labelMJ.setObjectName(u"labelMJ")
        self.labelMJ.setGeometry(QRect(810, 10, 61, 21))
        self.labelMJ.setFont(font1)
        self.labelMJ.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_bg, "")
        self.tab_kayu = QWidget()
        self.tab_kayu.setObjectName(u"tab_kayu")
        self.pbKayu = QPushButton(self.tab_kayu)
        self.pbKayu.setObjectName(u"pbKayu")
        self.pbKayu.setGeometry(QRect(580, 10, 93, 28))
        self.pbKayu.setFont(font1)
        self.pilihMDK = QComboBox(self.tab_kayu)
        self.pilihMDK.setObjectName(u"pilihMDK")
        self.pilihMDK.setGeometry(QRect(90, 40, 291, 22))
        self.pilihMJK = QComboBox(self.tab_kayu)
        self.pilihMJK.setObjectName(u"pilihMJK")
        self.pilihMJK.setGeometry(QRect(950, 40, 291, 22))
        self.mdKayu = QGraphicsView(self.tab_kayu)
        self.mdKayu.setObjectName(u"mdKayu")
        self.mdKayu.setGeometry(QRect(10, 70, 611, 221))
        self.mjKayu = QGraphicsView(self.tab_kayu)
        self.mjKayu.setObjectName(u"mjKayu")
        self.mjKayu.setGeometry(QRect(630, 70, 611, 221))
        self.fftKayu = QGraphicsView(self.tab_kayu)
        self.fftKayu.setObjectName(u"fftKayu")
        self.fftKayu.setGeometry(QRect(10, 300, 1231, 281))
        self.namaKayu = QLineEdit(self.tab_kayu)
        self.namaKayu.setObjectName(u"namaKayu")
        self.namaKayu.setGeometry(QRect(90, 10, 291, 22))
        self.namaKayu.setFont(font1)
        self.labelKayu = QLabel(self.tab_kayu)
        self.labelKayu.setObjectName(u"labelKayu")
        self.labelKayu.setGeometry(QRect(10, 10, 71, 21))
        self.labelKayu.setFont(font1)
        self.labelKayu.setAlignment(Qt.AlignCenter)
        self.labelMDK = QLabel(self.tab_kayu)
        self.labelMDK.setObjectName(u"labelMDK")
        self.labelMDK.setGeometry(QRect(10, 40, 61, 21))
        self.labelMDK.setFont(font1)
        self.labelMDK.setAlignment(Qt.AlignCenter)
        self.labelMJK = QLabel(self.tab_kayu)
        self.labelMJK.setObjectName(u"labelMJK")
        self.labelMJK.setGeometry(QRect(880, 40, 61, 21))
        self.labelMJK.setFont(font1)
        self.labelMJK.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_kayu, "")
        self.tab_af = QWidget()
        self.tab_af.setObjectName(u"tab_af")
        self.fftMulti = QGraphicsView(self.tab_af)
        self.fftMulti.setObjectName(u"fftMulti")
        self.fftMulti.setGeometry(QRect(10, 90, 1231, 491))
        self.pbUpload = QPushButton(self.tab_af)
        self.pbUpload.setObjectName(u"pbUpload")
        self.pbUpload.setGeometry(QRect(10, 10, 93, 28))
        self.pbUpload.setFont(font1)
        self.pbHapus = QPushButton(self.tab_af)
        self.pbHapus.setObjectName(u"pbHapus")
        self.pbHapus.setGeometry(QRect(570, 50, 93, 28))
        self.pbHapus.setFont(font1)
        self.file_list = QListWidget(self.tab_af)
        self.file_list.setObjectName(u"file_list")
        self.file_list.setGeometry(QRect(120, 10, 441, 71))
        self.pbRefresh = QPushButton(self.tab_af)
        self.pbRefresh.setObjectName(u"pbRefresh")
        self.pbRefresh.setGeometry(QRect(570, 10, 93, 28))
        self.pbRefresh.setFont(font1)
        self.tabWidget.addTab(self.tab_af, "")
        self.judul = QLabel(self.centralwidget)
        self.judul.setObjectName(u"judul")
        self.judul.setGeometry(QRect(30, 19, 1061, 41))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.judul.setFont(font2)
        self.judul.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1303, 19))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pbBG.setText(QCoreApplication.translate("MainWindow", u"Rekam", None))
        self.labelMD.setText(QCoreApplication.translate("MainWindow", u"Pilih MD", None))
        self.labelMJ.setText(QCoreApplication.translate("MainWindow", u"Pilih MJ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bg), QCoreApplication.translate("MainWindow", u"BACKGROUND", None))
        self.pbKayu.setText(QCoreApplication.translate("MainWindow", u"Rekam", None))
        self.labelKayu.setText(QCoreApplication.translate("MainWindow", u"Nama Kayu", None))
        self.labelMDK.setText(QCoreApplication.translate("MainWindow", u"Pilih MD", None))
        self.labelMJK.setText(QCoreApplication.translate("MainWindow", u"Pilih MJ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kayu), QCoreApplication.translate("MainWindow", u"KAYU", None))
        self.pbUpload.setText(QCoreApplication.translate("MainWindow", u"Unggah File", None))
        self.pbHapus.setText(QCoreApplication.translate("MainWindow", u"Hapus", None))
        self.pbRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_af), QCoreApplication.translate("MainWindow", u"ANALISIS FREKUENSI", None))
        self.judul.setText(QCoreApplication.translate("MainWindow", u"SISTEM UJI TIDAK MERUSAK KETEGUHAN LENTUR STATIK KAYU", None))
    # retranslateUi

