# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt5.QtWidgets import (QApplication, QComboBox, QGraphicsView, QGridLayout,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet(u"background-color: #808080;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 90, 1581, 781))
        self.tabWidget.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"background-color: #333333;")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setIconSize(QSize(100, 100))
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_bg = QWidget()
        self.tab_bg.setObjectName(u"tab_bg")
        self.pbBG = QPushButton(self.tab_bg)
        self.pbBG.setObjectName(u"pbBG")
        self.pbBG.setGeometry(QRect(680, 5, 93, 29))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.pbBG.setFont(font1)
        self.pbBG.setStyleSheet(u"background-color: red;")
        self.pilihMD = QComboBox(self.tab_bg)
        self.pilihMD.setObjectName(u"pilihMD")
        self.pilihMD.setGeometry(QRect(70, 20, 361, 22))
        self.pilihMD.setFont(font1)
        self.pilihMD.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.pilihMJ = QComboBox(self.tab_bg)
        self.pilihMJ.setObjectName(u"pilihMJ")
        self.pilihMJ.setGeometry(QRect(1210, 20, 361, 22))
        self.pilihMJ.setFont(font1)
        self.pilihMJ.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.mdBG = QGraphicsView(self.tab_bg)
        self.mdBG.setObjectName(u"mdBG")
        self.mdBG.setGeometry(QRect(10, 50, 731, 261))
        self.mdBG.setStyleSheet(u"background-color: black;")
        self.mjBG = QGraphicsView(self.tab_bg)
        self.mjBG.setObjectName(u"mjBG")
        self.mjBG.setGeometry(QRect(840, 50, 731, 261))
        self.mjBG.setStyleSheet(u"background-color: black;")
        self.fftBG = QGraphicsView(self.tab_bg)
        self.fftBG.setObjectName(u"fftBG")
        self.fftBG.setGeometry(QRect(10, 320, 1561, 401))
        self.fftBG.setStyleSheet(u"background-color: black;")
        self.labelMD = QLabel(self.tab_bg)
        self.labelMD.setObjectName(u"labelMD")
        self.labelMD.setGeometry(QRect(10, 20, 61, 21))
        self.labelMD.setFont(font1)
        self.labelMD.setStyleSheet(u"COLOR: WHITE;")
        self.labelMD.setAlignment(Qt.AlignCenter)
        self.labelMJ = QLabel(self.tab_bg)
        self.labelMJ.setObjectName(u"labelMJ")
        self.labelMJ.setGeometry(QRect(1150, 20, 61, 21))
        self.labelMJ.setFont(font1)
        self.labelMJ.setStyleSheet(u"COLOR: WHITE;")
        self.labelMJ.setAlignment(Qt.AlignCenter)
        self.pbBGUpload = QPushButton(self.tab_bg)
        self.pbBGUpload.setObjectName(u"pbBGUpload")
        self.pbBGUpload.setGeometry(QRect(810, 5, 93, 29))
        self.pbBGUpload.setFont(font1)
        self.pbBGUpload.setStyleSheet(u"background-color: yellow;")
        self.label = QLabel(self.tab_bg)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 55, 711, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.label.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.tab_bg)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(850, 55, 711, 31))
        self.label_5.setFont(font2)
        self.label_5.setStyleSheet(u"color: white; \n"
"background-color: black;")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.tab_bg)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 325, 1541, 31))
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_bg, "")
        self.tab_kayu = QWidget()
        self.tab_kayu.setObjectName(u"tab_kayu")
        self.pbKayu = QPushButton(self.tab_kayu)
        self.pbKayu.setObjectName(u"pbKayu")
        self.pbKayu.setGeometry(QRect(50, 330, 93, 26))
        self.pbKayu.setFont(font1)
        self.pbKayu.setStyleSheet(u"background-color: red;")
        self.pilihMDK = QComboBox(self.tab_kayu)
        self.pilihMDK.setObjectName(u"pilihMDK")
        self.pilihMDK.setGeometry(QRect(70, 40, 361, 22))
        self.pilihMDK.setFont(font1)
        self.pilihMDK.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.pilihMJK = QComboBox(self.tab_kayu)
        self.pilihMJK.setObjectName(u"pilihMJK")
        self.pilihMJK.setGeometry(QRect(1210, 40, 361, 22))
        self.pilihMJK.setFont(font1)
        self.pilihMJK.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.mdKayu = QGraphicsView(self.tab_kayu)
        self.mdKayu.setObjectName(u"mdKayu")
        self.mdKayu.setGeometry(QRect(10, 70, 731, 251))
        self.mdKayu.setStyleSheet(u"background-color: black;")
        self.mjKayu = QGraphicsView(self.tab_kayu)
        self.mjKayu.setObjectName(u"mjKayu")
        self.mjKayu.setGeometry(QRect(840, 70, 731, 251))
        self.mjKayu.setStyleSheet(u"background-color: black;")
        self.fftKayu = QGraphicsView(self.tab_kayu)
        self.fftKayu.setObjectName(u"fftKayu")
        self.fftKayu.setGeometry(QRect(360, 330, 1211, 391))
        self.fftKayu.setStyleSheet(u"background-color: black;")
        self.namaKayu = QLineEdit(self.tab_kayu)
        self.namaKayu.setObjectName(u"namaKayu")
        self.namaKayu.setGeometry(QRect(90, 10, 301, 22))
        self.namaKayu.setFont(font1)
        self.namaKayu.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.labelKayu = QLabel(self.tab_kayu)
        self.labelKayu.setObjectName(u"labelKayu")
        self.labelKayu.setGeometry(QRect(10, 10, 71, 21))
        self.labelKayu.setFont(font1)
        self.labelKayu.setStyleSheet(u"color: white;")
        self.labelKayu.setAlignment(Qt.AlignCenter)
        self.labelMDK = QLabel(self.tab_kayu)
        self.labelMDK.setObjectName(u"labelMDK")
        self.labelMDK.setGeometry(QRect(10, 40, 61, 21))
        self.labelMDK.setFont(font1)
        self.labelMDK.setStyleSheet(u"color: white;")
        self.labelMDK.setAlignment(Qt.AlignCenter)
        self.labelMJK = QLabel(self.tab_kayu)
        self.labelMJK.setObjectName(u"labelMJK")
        self.labelMJK.setGeometry(QRect(1150, 40, 61, 21))
        self.labelMJK.setFont(font1)
        self.labelMJK.setStyleSheet(u"color: white;")
        self.labelMJK.setAlignment(Qt.AlignCenter)
        self.widget = QWidget(self.tab_kayu)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 370, 341, 351))
        self.widget.setStyleSheet(u"background-color: white;\n"
"border:1px solid rgb(184, 184, 184);")
        self.gridLayout = QGridLayout(self.widget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.name_label = QLabel(self.widget)
        self.name_label.setObjectName(u"name_label")
        font3 = QFont()
        font3.setPointSize(10)
        self.name_label.setFont(font3)
        self.name_label.setStyleSheet(u"background-color: #808080;")
        self.name_label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.name_label, 0, 1, 1, 1)

        self.kelas_kuat_label = QLabel(self.widget)
        self.kelas_kuat_label.setObjectName(u"kelas_kuat_label")
        self.kelas_kuat_label.setFont(font3)
        self.kelas_kuat_label.setStyleSheet(u"background-color: #808080;")
        self.kelas_kuat_label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.kelas_kuat_label, 3, 1, 1, 1)

        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(16777215, 16777215))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.label_3.setFont(font4)
        self.label_3.setStyleSheet(u"background-color: #808080;")
        self.label_3.setWordWrap(True)

        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)

        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font3)
        self.label_4.setStyleSheet(u"background-color: #808080;")

        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)

        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font4)
        self.label_2.setStyleSheet(u"background-color: #808080;")

        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.gain_label = QLabel(self.widget)
        self.gain_label.setObjectName(u"gain_label")
        self.gain_label.setStyleSheet(u"background-color: #808080;")
        self.gain_label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.gain_label, 2, 1, 1, 1)

        self.moe_label = QLabel(self.widget)
        self.moe_label.setObjectName(u"moe_label")
        self.moe_label.setFont(font3)
        self.moe_label.setStyleSheet(u"background-color: #808080;")
        self.moe_label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.moe_label, 4, 1, 1, 1)

        self.frequency_label = QLabel(self.widget)
        self.frequency_label.setObjectName(u"frequency_label")
        self.frequency_label.setFont(font3)
        self.frequency_label.setStyleSheet(u"background-color: #808080;")
        self.frequency_label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.frequency_label, 1, 1, 1, 1)

        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setStyleSheet(u"background-color: #808080;")

        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)

        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font3)
        self.label_12.setStyleSheet(u"background-color: #808080;")
        self.label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)

        self.label_13 = QLabel(self.widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font3)
        self.label_13.setStyleSheet(u"background-color: #808080;")
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)

        self.kelas_moe_label = QLabel(self.widget)
        self.kelas_moe_label.setObjectName(u"kelas_moe_label")
        self.kelas_moe_label.setFont(font3)
        self.kelas_moe_label.setStyleSheet(u"background-color: #808080;")
        self.kelas_moe_label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.kelas_moe_label, 5, 1, 1, 1)

        self.pbKayu_analyze = QPushButton(self.tab_kayu)
        self.pbKayu_analyze.setObjectName(u"pbKayu_analyze")
        self.pbKayu_analyze.setGeometry(QRect(210, 330, 111, 26))
        self.pbKayu_analyze.setFont(font1)
        self.pbKayu_analyze.setStyleSheet(u"background-color: yellow;")
        self.label_7 = QLabel(self.tab_kayu)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 75, 711, 31))
        self.label_7.setFont(font2)
        self.label_7.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.tab_kayu)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(850, 75, 711, 31))
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.tab_kayu)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(370, 335, 1191, 31))
        self.label_9.setFont(font2)
        self.label_9.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_kayu, "")
        self.tab_af = QWidget()
        self.tab_af.setObjectName(u"tab_af")
        self.pbUpload = QPushButton(self.tab_af)
        self.pbUpload.setObjectName(u"pbUpload")
        self.pbUpload.setGeometry(QRect(10, 60, 93, 28))
        self.pbUpload.setFont(font1)
        self.pbUpload.setStyleSheet(u"background-color: yellow;")
        self.pbHapus = QPushButton(self.tab_af)
        self.pbHapus.setObjectName(u"pbHapus")
        self.pbHapus.setGeometry(QRect(890, 80, 93, 28))
        self.pbHapus.setFont(font1)
        self.pbHapus.setStyleSheet(u"background-color: red;")
        self.file_list = QListWidget(self.tab_af)
        self.file_list.setObjectName(u"file_list")
        self.file_list.setGeometry(QRect(110, 20, 771, 111))
        self.file_list.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.pbRefresh = QPushButton(self.tab_af)
        self.pbRefresh.setObjectName(u"pbRefresh")
        self.pbRefresh.setGeometry(QRect(890, 40, 93, 28))
        self.pbRefresh.setFont(font1)
        self.pbRefresh.setStyleSheet(u"background-color: #ADD8E6;")
        self.fftMulti = QGraphicsView(self.tab_af)
        self.fftMulti.setObjectName(u"fftMulti")
        self.fftMulti.setGeometry(QRect(490, 150, 1081, 571))
        self.fftMulti.setStyleSheet(u"background-color: black;")
        self.tableAnalysis = QTableWidget(self.tab_af)
        self.tableAnalysis.setObjectName(u"tableAnalysis")
        self.tableAnalysis.setGeometry(QRect(10, 150, 461, 571))
        self.tableAnalysis.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.tableAnalysis.setLineWidth(1)
        self.tableAnalysis.setAlternatingRowColors(False)
        self.tableAnalysis.setWordWrap(False)
        self.tableAnalysis.setRowCount(0)
        self.tableAnalysis.horizontalHeader().setVisible(False)
        self.tableAnalysis.horizontalHeader().setCascadingSectionResizes(True)
        self.tableAnalysis.horizontalHeader().setMinimumSectionSize(50)
        self.tableAnalysis.horizontalHeader().setHighlightSections(False)
        self.tableAnalysis.horizontalHeader().setStretchLastSection(False)
        self.tableAnalysis.verticalHeader().setCascadingSectionResizes(False)
        self.label_10 = QLabel(self.tab_af)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(490, 155, 1071, 31))
        self.label_10.setFont(font2)
        self.label_10.setStyleSheet(u"color: white;\n"
"background-color: black;")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_af, "")
        self.judul = QLabel(self.centralwidget)
        self.judul.setObjectName(u"judul")
        self.judul.setGeometry(QRect(10, 10, 1600, 41))
        font5 = QFont()
        font5.setPointSize(16)
        font5.setBold(True)
        self.judul.setFont(font5)
        self.judul.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1600, 20))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NDT Static Bending Strength of Wood", None))
        self.pbBG.setText(QCoreApplication.translate("MainWindow", u"Rekam", None))
        self.labelMD.setText(QCoreApplication.translate("MainWindow", u"Pilih MD", None))
        self.labelMJ.setText(QCoreApplication.translate("MainWindow", u"Pilih MJ", None))
        self.pbBGUpload.setText(QCoreApplication.translate("MainWindow", u"Unggah", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sinyal Audio Mic Dekat dalam Domain Waktu", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Sinyal Audio Mic Jauh dalam Domain Waktu", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Analisis Frekuensi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bg), QCoreApplication.translate("MainWindow", u"SINYAL BACKGROUND", None))
        self.pbKayu.setText(QCoreApplication.translate("MainWindow", u"Rekam", None))
        self.labelKayu.setText(QCoreApplication.translate("MainWindow", u"Nama Kayu", None))
        self.labelMDK.setText(QCoreApplication.translate("MainWindow", u"Pilih MD", None))
        self.labelMJK.setText(QCoreApplication.translate("MainWindow", u"Pilih MJ", None))
        self.name_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.kelas_kuat_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Frekuensi resonansi:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Kelas Kuat:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Kayu:", None))
        self.gain_label.setText(QCoreApplication.translate("MainWindow", u"0 dB", None))
        self.moe_label.setText(QCoreApplication.translate("MainWindow", u"0 MPa", None))
        self.frequency_label.setText(QCoreApplication.translate("MainWindow", u"0 Hz", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Nilai Gain", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Nilai MOE:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Kelas MOE:", None))
        self.kelas_moe_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pbKayu_analyze.setText(QCoreApplication.translate("MainWindow", u"Analisis", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Sinyal Audio Mic Dekat Dalam Domain Waktu", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Sinyal Audio Mic Jauh Dalam Domain Waktu", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Analisis Frekuensi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kayu), QCoreApplication.translate("MainWindow", u"SINYAL KAYU", None))
        self.pbUpload.setText(QCoreApplication.translate("MainWindow", u"Unggah File", None))
        self.pbHapus.setText(QCoreApplication.translate("MainWindow", u"Hapus", None))
        self.pbRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Analisis Frekuensi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_af), QCoreApplication.translate("MainWindow", u"ANALISIS FREKUENSI", None))
        self.judul.setText(QCoreApplication.translate("MainWindow", u"SISTEM UJI TIDAK MERUSAK KETEGUHAN LENTUR STATIK KAYU", None))
    # retranslateUi

