# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt5.QtWidgets import (QApplication, QComboBox, QGraphicsView, QGridLayout,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1564, 853)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 60, 1551, 701))
        self.tabWidget.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setIconSize(QSize(100, 100))
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_bg = QWidget()
        self.tab_bg.setObjectName(u"tab_bg")
        self.pbBG = QPushButton(self.tab_bg)
        self.pbBG.setObjectName(u"pbBG")
        self.pbBG.setGeometry(QRect(670, 10, 93, 29))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.pbBG.setFont(font1)
        self.pbBG.setStyleSheet(u"b")
        self.pilihMD = QComboBox(self.tab_bg)
        self.pilihMD.setObjectName(u"pilihMD")
        self.pilihMD.setGeometry(QRect(70, 20, 361, 22))
        self.pilihMD.setFont(font1)
        self.pilihMJ = QComboBox(self.tab_bg)
        self.pilihMJ.setObjectName(u"pilihMJ")
        self.pilihMJ.setGeometry(QRect(1180, 20, 361, 22))
        self.pilihMJ.setFont(font1)
        self.mdBG = QGraphicsView(self.tab_bg)
        self.mdBG.setObjectName(u"mdBG")
        self.mdBG.setGeometry(QRect(10, 50, 651, 241))
        self.mjBG = QGraphicsView(self.tab_bg)
        self.mjBG.setObjectName(u"mjBG")
        self.mjBG.setGeometry(QRect(890, 50, 651, 241))
        self.fftBG = QGraphicsView(self.tab_bg)
        self.fftBG.setObjectName(u"fftBG")
        self.fftBG.setGeometry(QRect(10, 300, 1531, 361))
        self.labelMD = QLabel(self.tab_bg)
        self.labelMD.setObjectName(u"labelMD")
        self.labelMD.setGeometry(QRect(10, 20, 61, 21))
        self.labelMD.setFont(font1)
        self.labelMD.setAlignment(Qt.AlignCenter)
        self.labelMJ = QLabel(self.tab_bg)
        self.labelMJ.setObjectName(u"labelMJ")
        self.labelMJ.setGeometry(QRect(1110, 20, 61, 21))
        self.labelMJ.setFont(font1)
        self.labelMJ.setAlignment(Qt.AlignCenter)
        self.pbBGUpload = QPushButton(self.tab_bg)
        self.pbBGUpload.setObjectName(u"pbBGUpload")
        self.pbBGUpload.setGeometry(QRect(790, 10, 93, 29))
        self.pbBGUpload.setFont(font1)
        self.pbBGUpload.setStyleSheet(u"b")
        self.tabWidget.addTab(self.tab_bg, "")
        self.tab_kayu = QWidget()
        self.tab_kayu.setObjectName(u"tab_kayu")
        self.pbKayu = QPushButton(self.tab_kayu)
        self.pbKayu.setObjectName(u"pbKayu")
        self.pbKayu.setGeometry(QRect(700, 30, 93, 26))
        self.pbKayu.setFont(font1)
        self.pilihMDK = QComboBox(self.tab_kayu)
        self.pilihMDK.setObjectName(u"pilihMDK")
        self.pilihMDK.setGeometry(QRect(70, 40, 361, 22))
        self.pilihMDK.setFont(font1)
        self.pilihMJK = QComboBox(self.tab_kayu)
        self.pilihMJK.setObjectName(u"pilihMJK")
        self.pilihMJK.setGeometry(QRect(1120, 40, 361, 22))
        self.pilihMJK.setFont(font1)
        self.mdKayu = QGraphicsView(self.tab_kayu)
        self.mdKayu.setObjectName(u"mdKayu")
        self.mdKayu.setGeometry(QRect(10, 70, 621, 221))
        self.mjKayu = QGraphicsView(self.tab_kayu)
        self.mjKayu.setObjectName(u"mjKayu")
        self.mjKayu.setGeometry(QRect(860, 70, 621, 221))
        self.fftKayu = QGraphicsView(self.tab_kayu)
        self.fftKayu.setObjectName(u"fftKayu")
        self.fftKayu.setGeometry(QRect(360, 300, 1181, 361))
        self.namaKayu = QLineEdit(self.tab_kayu)
        self.namaKayu.setObjectName(u"namaKayu")
        self.namaKayu.setGeometry(QRect(90, 10, 301, 22))
        self.namaKayu.setFont(font1)
        self.labelKayu = QLabel(self.tab_kayu)
        self.labelKayu.setObjectName(u"labelKayu")
        self.labelKayu.setGeometry(QRect(10, 10, 71, 21))
        self.labelKayu.setFont(font1)
        self.labelKayu.setAlignment(Qt.AlignCenter)
        self.labelMDK = QLabel(self.tab_kayu)
        self.labelMDK.setObjectName(u"labelMDK")
        self.labelMDK.setGeometry(QRect(10, 40, 61, 21))
        self.labelMDK.setFont(font1)
        self.labelMDK.setAlignment(Qt.AlignCenter)
        self.labelMJK = QLabel(self.tab_kayu)
        self.labelMJK.setObjectName(u"labelMJK")
        self.labelMJK.setGeometry(QRect(1050, 40, 61, 21))
        self.labelMJK.setFont(font1)
        self.labelMJK.setAlignment(Qt.AlignCenter)
        self.widget = QWidget(self.tab_kayu)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 330, 341, 251))
        self.widget.setStyleSheet(u"background-color:white;\n"
"border:1px solid rgb(184, 184, 184);")
        self.gridLayout = QGridLayout(self.widget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(16777215, 16777215))
        font2 = QFont()
        font2.setPointSize(10)
        self.label_3.setFont(font2)
        self.label_3.setWordWrap(True)

        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)

        self.frequency_label = QLabel(self.widget)
        self.frequency_label.setObjectName(u"frequency_label")

        self.gridLayout.addWidget(self.frequency_label, 1, 1, 1, 1)

        self.kelas_label = QLabel(self.widget)
        self.kelas_label.setObjectName(u"kelas_label")

        self.gridLayout.addWidget(self.kelas_label, 2, 1, 1, 1)

        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font2)

        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font2)

        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.name_label = QLabel(self.widget)
        self.name_label.setObjectName(u"name_label")

        self.gridLayout.addWidget(self.name_label, 0, 1, 1, 1)

        self.pbKayu_analyze = QPushButton(self.tab_kayu)
        self.pbKayu_analyze.setObjectName(u"pbKayu_analyze")
        self.pbKayu_analyze.setGeometry(QRect(130, 300, 101, 26))
        self.pbKayu_analyze.setFont(font1)
        self.tabWidget.addTab(self.tab_kayu, "")
        self.tab_af = QWidget()
        self.tab_af.setObjectName(u"tab_af")
        self.pbUpload = QPushButton(self.tab_af)
        self.pbUpload.setObjectName(u"pbUpload")
        self.pbUpload.setGeometry(QRect(10, 40, 93, 28))
        self.pbUpload.setFont(font1)
        self.pbHapus = QPushButton(self.tab_af)
        self.pbHapus.setObjectName(u"pbHapus")
        self.pbHapus.setGeometry(QRect(890, 50, 93, 28))
        self.pbHapus.setFont(font1)
        self.file_list = QListWidget(self.tab_af)
        self.file_list.setObjectName(u"file_list")
        self.file_list.setGeometry(QRect(110, 20, 771, 71))
        self.pbRefresh = QPushButton(self.tab_af)
        self.pbRefresh.setObjectName(u"pbRefresh")
        self.pbRefresh.setGeometry(QRect(890, 20, 93, 28))
        self.pbRefresh.setFont(font1)
        self.fftMulti = QGraphicsView(self.tab_af)
        self.fftMulti.setObjectName(u"fftMulti")
        self.fftMulti.setGeometry(QRect(440, 110, 1101, 551))
        self.tableAnalysis = QTableWidget(self.tab_af)
        self.tableAnalysis.setObjectName(u"tableAnalysis")
        self.tableAnalysis.setGeometry(QRect(10, 110, 421, 551))
        self.tableAnalysis.setLineWidth(1)
        self.tableAnalysis.setAlternatingRowColors(False)
        self.tableAnalysis.setWordWrap(False)
        self.tableAnalysis.setRowCount(0)
        self.tableAnalysis.horizontalHeader().setVisible(False)
        self.tableAnalysis.horizontalHeader().setCascadingSectionResizes(True)
        self.tableAnalysis.horizontalHeader().setMinimumSectionSize(50)
        self.tableAnalysis.horizontalHeader().setHighlightSections(False)
        self.tableAnalysis.horizontalHeader().setStretchLastSection(False)
        self.tableAnalysis.verticalHeader().setCascadingSectionResizes(False)
        self.tabWidget.addTab(self.tab_af, "")
        self.judul = QLabel(self.centralwidget)
        self.judul.setObjectName(u"judul")
        self.judul.setGeometry(QRect(10, 10, 1491, 41))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(True)
        self.judul.setFont(font3)
        self.judul.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1564, 20))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NDT Static Bending Strength of Wood", None))
        self.pbBG.setText(QCoreApplication.translate("MainWindow", u"Rekam", None))
        self.labelMD.setText(QCoreApplication.translate("MainWindow", u"Pilih MD", None))
        self.labelMJ.setText(QCoreApplication.translate("MainWindow", u"Pilih MJ", None))
        self.pbBGUpload.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bg), QCoreApplication.translate("MainWindow", u"SINYAL BACKGROUND", None))
        self.pbKayu.setText(QCoreApplication.translate("MainWindow", u"Rekam", None))
        self.labelKayu.setText(QCoreApplication.translate("MainWindow", u"Nama Kayu", None))
        self.labelMDK.setText(QCoreApplication.translate("MainWindow", u"Pilih MD", None))
        self.labelMJK.setText(QCoreApplication.translate("MainWindow", u"Pilih MJ", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Frekuensi resonansi:", None))
        self.frequency_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.kelas_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Kelas Kuat:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Kayu:", None))
        self.name_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pbKayu_analyze.setText(QCoreApplication.translate("MainWindow", u"Analyze", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kayu), QCoreApplication.translate("MainWindow", u"SINYAL KAYU", None))
        self.pbUpload.setText(QCoreApplication.translate("MainWindow", u"Unggah File", None))
        self.pbHapus.setText(QCoreApplication.translate("MainWindow", u"Hapus", None))
        self.pbRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_af), QCoreApplication.translate("MainWindow", u"ANALISIS FREKUENSI", None))
        self.judul.setText(QCoreApplication.translate("MainWindow", u"SISTEM UJI TIDAK MERUSAK KETEGUHAN LENTUR STATIK KAYU", None))
    # retranslateUi

